# Generated by Django 2.0.8 on 2018-10-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('foto', models.ImageField(upload_to='foto', verbose_name='Фото')),
                ('age', models.IntegerField(verbose_name='Возраст')),
            ],
        ),
        migrations.CreateModel(
            name='PollPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now_count', models.IntegerField(default=0, verbose_name='')),
                ('person', models.ForeignKey(on_delete='PROTECT', related_name='pers', to='app.Person', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('startdate', models.DateField(verbose_name='Дата начала')),
                ('enddate', models.DateField(verbose_name='Дата окончания')),
                ('max_count', models.IntegerField(verbose_name='Максимальное количество голосов')),
                ('person', models.ManyToManyField(related_name='person', through='app.PollPerson', to='app.Person')),
            ],
        ),
        migrations.AddField(
            model_name='pollperson',
            name='polls',
            field=models.ForeignKey(on_delete='PROTECT', related_name='poll', to='app.Polls', verbose_name=''),
        ),
    ]
